retaildevcrews/loderunner

ValidationTest/Main.cs
ValidationTest/Model/config.cs
core/CommandLine.cs

- Prometheus updates per design review
-

Prometheus updates

---

.github/workflows/ngsa.yaml

- added ci-cd to publish to ghcr.io
- Closes retaildevcrews/ngsa#497

added ci-cd

---

.github/workflows/ngsa.yaml

@bartr same here, change is already in the branch. Went ahead and made the PR

updated ci

---

src/Program.cs
src/ValidationTest/Main.cs
src/core/CommandLine.cs
src/core/Parsers.cs

The delay-start argument logic was improved to accept -1 and enter a wait state to support future spike work.
Closes: [Issue#231 ](https://github.com/retaildevcrews/wcnp/issues/231)

Added Standby flag to LR

---

Ngsa.LodeRunner.csproj
src/Program.cs
src/events/ClientStatusEventArgs.cs
src/events/ProcessingEventBus.cs

Closes https://github.com/retaildevcrews/wcnp/issues/232

Creating Status Update Event Infrastructure

---

src/Program.cs

Will not execute capabilities still in the process of being developed based on directive definition.

Conditional Comp for Release

---

baseline.json
memory-baseline.json

Reopening the PR, now that ngsa-java version output is uniform with that of the nsga dotnet's.

Version test

---

Ngsa.LodeRunner.csproj
src/Program.cs
src/events/ClientStatusEventArgs.cs
src/events/ProcessingEventBus.cs

Closes https://github.com/retaildevcrews/wcnp/issues/316

Addressing some linter issues

---

src/Program.cs

Removed Windows native dll reference
References : [Issue #329](https://github.com/retaildevcrews/wcnp/issues/329)

Removed Windows native dll reference

---

src/ValidationTest/Main.cs
src/ValidationTest/Model/TimerRequestState.cs
src/ValidationTest/Model/config.cs
src/core/CommandLine.cs

Adding option to clear dotnet level DNS Cache

Clear dns cache

---

.github/workflows/ngsa.yaml

Doing this temporarily while the codebase undergoes merging and refactoring.

Disable Push

---

.github/workflows/ngsa.yaml
autogitops/autogitops.json
autogitops/ngsa-preprod.yaml

References: https://github.com/retaildevcrews/wcnp/issues/373

Added AutoGitops

---

.github/workflows/ngsa.yaml
autogitops/autogitops.json
autogitops/ngsa-preprod.yaml

- To add central cluster for autogitops in loderunner.
- Replaced pod with deployment
- References https://github.com/retaildevcrews/wcnp/issues/373

Added central cluster and replaced pod with deployment

---

docs/MemoryCachePerfMetrics.md

Record the results different solutions tested in a markdown file in the docs folder
- Closes [#375](https://github.com/retaildevcrews/wcnp/issues/375)

Record Memory Cache Performance Metrics in a MD file.

---

.github/workflows/loderunner-api.yaml

Added Integration testing Steps for LodeRunner.API and LodeRunner
- Closes [#464](https://github.com/retaildevcrews/wcnp/issues/464)

Added Integration testing Steps to LodeRunner.API workflow

---

src/LodeRunner.API/LodeRunnerApi.xml
src/LodeRunner.API/src/Controllers/ClientsController.cs
src/LodeRunner.API/src/Controllers/LoadTestConfigController.cs
src/LodeRunner.API/src/Core/NgsaLog.cs
src/LodeRunner.API/src/Data/Cache/LRAPICache.cs
src/LodeRunner.API/src/Handlers/ExceptionMiddleware/GlobalException.cs
src/LodeRunner.API/src/Handlers/ResultHandler.cs
src/LodeRunner.API/src/Interfaces/ILRAPICache.cs
src/LodeRunner.API/src/Program.cs
src/LodeRunner.Core/Cache/BaseAppCache.cs
src/LodeRunner.Core/Interfaces/IAppCache.cs

Make LodeRunner.API Calls Async
- Closes [#494](https://github.com/retaildevcrews/wcnp/issues/494)

Make LodeRunner.API Calls Async

---

src/LodeRunner.UI/src/components/App/index.js
src/LodeRunner.UI/src/components/App/styles.css
src/LodeRunner.UI/src/components/ClientDetails/index.js
src/LodeRunner.UI/src/components/Clients/index.js
src/LodeRunner.UI/src/components/Configs/index.js
src/LodeRunner.UI/src/components/Configs/styles.css
src/LodeRunner.UI/src/components/ContentPage/index.js
src/LodeRunner.UI/src/components/Modal/index.js
src/LodeRunner.UI/src/components/Modal/styles.css
src/LodeRunner.UI/src/components/PendingFeature/index.js
src/LodeRunner.UI/src/components/PendingFeature/styles.css
src/LodeRunner.UI/src/components/Trash/index.js
src/LodeRunner.UI/src/contexts/clients.js
src/LodeRunner.UI/src/contexts/configs.js
src/LodeRunner.UI/src/contexts/display.js
src/LodeRunner.UI/src/contexts/index.js
src/LodeRunner.UI/src/models/index.js
src/LodeRunner.UI/src/services/api-service.js

Display a list of existing Configs. The UI uses mocked data and not the LodeRunner.API for now.
- Closes [#419](https://github.com/retaildevcrews/wcnp/issues/419)

List existing configs in LodeRunner.UI with mocked data

---

src/LodeRunner.UI/README.md
src/LodeRunner.UI/package-lock.json
src/LodeRunner.UI/package.json
src/LodeRunner.UI/src/components/App/index.js
src/LodeRunner.UI/src/components/App/styles.css
src/LodeRunner.UI/src/components/Clients/index.js
src/LodeRunner.UI/src/components/ConfigForm/index.js
src/LodeRunner.UI/src/components/ConfigForm/styles.css
src/LodeRunner.UI/src/components/Configs/index.js
src/LodeRunner.UI/src/contexts/index.js
src/LodeRunner.UI/src/services/configs.js
src/LodeRunner.UI/src/services/configs.test.js
src/LodeRunner.UI/src/services/utilities.js

Delete LoadTestConfig via LodeRunner.UI
- Closes https://github.com/retaildevcrews/wcnp/issues/421

Delete LoadTestConfig via LodeRunner.UI

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
src/LodeRunner/src/Services/LodeRunnerService.cs

Fixed delayStart bug and disabled two Integration Tests
- Closes #515
- References #502 (We will re-enable Integration Test as part of #502)

Fixed delayStart bug and disabled two Integration Tests

---

.gitignore
Makefile
README.md
src/LodeRunner.API/.dockerignore
src/LodeRunner.API/README.md
src/LodeRunner.Data/README.md
src/LodeRunner.UI/.dockerignore
src/LodeRunner.UI/.eslintrc.json
src/LodeRunner.UI/README.md
src/LodeRunner.UI/babel.config.js
src/LodeRunner.UI/jest.config.js
src/LodeRunner.UI/package-lock.json
src/LodeRunner.UI/package.json
src/LodeRunner.UI/public/index.html
src/LodeRunner.UI/src/components/App/styles.css
src/LodeRunner.UI/src/components/Clients/styles.css
src/LodeRunner.UI/src/index.css
src/LodeRunner/.dockerignore
src/LodeRunner/README.md

Update LodeRunner.UI dev experience instructions

Update LodeRunner.UI dev experience instructions

---

docs/ParameterValidation.md
src/LodeRunner.API/LodeRunnerApi.xml
src/LodeRunner.API/src/Core/SystemConstants.cs
src/LodeRunner.API/src/Data/Cache/LRAPICache.cs
src/LodeRunner.API/src/Utilities/Parameters/ClientParameters.cs
src/LodeRunner.API/src/Utilities/Parameters/ValidationError.cs

Use a single method to validate ClientStatus ID, both in LRAPICache and ClientsController
Validate entire ClientStatus object before inserting in cache
- Closes https://github.com/retaildevcrews/wcnp/issues/461

Refactor client status id validation

---

src/LodeRunner.Core/Models/LoadTestConfig.cs

Remove the unnecessary [Required] attribute for DelayedStart property

Removed Required Attributes from DelayedStart

---

src/LodeRunner.UI/package.json
src/LodeRunner.UI/src/components/App/index.js
src/LodeRunner.UI/src/components/Clients/index.js
src/LodeRunner.UI/src/services/clients.js
src/LodeRunner.UI/src/services/configs.js
src/LodeRunner.UI/src/services/utilities.js
src/LodeRunner.UI/src/services/utilities.test.js

Update an API utility function to not throw an error when the API response code is a 204, No Content. Previously, the behavior was to throw an error. Now it will return `undefined`. New tests were added to cover new and existing behavior.
- Closes https://github.com/retaildevcrews/wcnp/issues/521

Return undefined when for response body when API response is 204, No Content.

---

src/LodeRunner.Core/Interfaces/ILRConfig.cs
src/LodeRunner.Core/LodeRunner.Core.xml
src/LodeRunner/src/Services/LodeRunnerService.cs
src/LodeRunner/src/config.cs
src/LodeRunner/src/events/ProcessingEventBus.cs

Refactored the liveness timer by moving timer code to LodeRunnerService class
- Closes retaildevcrews/wcnp/issues/514

Refactored liveness timer

---

src/LodeRunner.UI/src/components/App/index.js
src/LodeRunner.UI/src/services/configs.js

Test UI implementation now that API endpoint was implemented.
- Closes #511

Removed mocked data and fixed endpoint name

---

deploy/loderunner/local/2-loderunner.yaml

Updayed loderunner deployment yaml to run loderunner in Client mode
- Closes #/retaildevcrews/wcnp/issues/528

Updated loderunner.yaml

---

src/LodeRunner.UI/src/services/configs.js

Test LodeRunner.UI update config and fixed endpoint name
- Closes #510

Test LodeRunner.UI update config and fixed endpoint name

---

src/LodeRunner.UI/src/components/ClientDetails/index.js
src/LodeRunner.UI/src/models/index.js

LodeRunner client has been updated to use client mode. Updated UI with client mode required and optional values. 
- Closes #/retaildevcrews/wcnp/issues/520

Updated UI with client mode required and optional values

---

Makefile
README.md
src/LodeRunner.UI/README.md
src/LodeRunner/README.md

Updated LodeRunner.UI startup instructions

Updated LodeRunner.UI startup instructions

---

src/LodeRunner.UI/src/components/ConfigForm/index.js
src/LodeRunner.UI/src/models/index.js
src/LodeRunner.UI/src/services/configs.js
src/LodeRunner.UI/src/services/configs.test.js
src/LodeRunner.UI/src/utilities/types.js
src/LodeRunner.UI/src/utilities/types.test.js

Update LodeRunner.UI with details from the updated mode compatibility table

Update LodeRunner.UI with mode compatibility table details

---

src/LodeRunner.UI/src/components/App/index.js
src/LodeRunner.UI/src/components/App/styles.css
src/LodeRunner.UI/src/components/CheckMarkIcon/index.js
src/LodeRunner.UI/src/components/ClientDetails/index.js
src/LodeRunner.UI/src/components/ClientDetails/styles.css
src/LodeRunner.UI/src/components/Clients/index.js
src/LodeRunner.UI/src/components/Clients/styles.css
src/LodeRunner.UI/src/components/ConfigForm/ArrayOfStringInput/index.js
src/LodeRunner.UI/src/components/ConfigForm/BooleanInput/index.js
src/LodeRunner.UI/src/components/ConfigForm/IntegerInput/index.js
src/LodeRunner.UI/src/components/ConfigForm/StringInput/index.js
src/LodeRunner.UI/src/components/ConfigForm/index.js
src/LodeRunner.UI/src/components/Configs/index.js
src/LodeRunner.UI/src/components/Configs/styles.css
src/LodeRunner.UI/src/components/Modal/index.js
src/LodeRunner.UI/src/components/PencilIcon/index.js
src/LodeRunner.UI/src/components/PlayIcon/index.js
src/LodeRunner.UI/src/components/TestSubmission/index.js
src/LodeRunner.UI/src/components/TestSubmission/styles.css
src/LodeRunner.UI/src/components/TrashIcon/index.js
src/LodeRunner.UI/src/models/index.js
src/LodeRunner.UI/src/services/configs.js
src/LodeRunner.UI/src/services/configs.test.js
src/LodeRunner.UI/src/services/testRun.js
src/LodeRunner.UI/src/utilities/constants.js

- Closes #[534](https://github.com/retaildevcrews/wcnp/issues/534)

LodeRunner.UI feature to post a test run.

---

README.md

I noticed the links to the sub README files for LodeRunner, LodeRunner.API, and LodeRunner.UI were incorrect.  
If it's preferred to add the mdlinkcheck workflow to this repo, I can add that to this PR as well or create a separate issue.
- Closes https://github.com/retaildevcrews/wcnp/issues/553

Updating links to repo source code readmes

---

src/LodeRunner/src/Services/LodeRunnerService.cs

…r; added note to explain OnStatusTimerEvent
Updated StatusUpdate calls in LodeRunnerService class to use LodeRunnerService as sender
- Closes retaildevcrews/wcnp/issues/526

Updated StatusUpdate calls 

---

src/LodeRunner.API/src/Core/SystemConstants.cs

Updated error message for queries with invalid clientStatusId
- Closes retaildevcrews/wcnp/issues/545

Updated clientStatusId error message

---

src/LodeRunner.API/LodeRunner.API.csproj
src/LodeRunner.API/README.md
src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
src/LodeRunner.API/src/Core/NgsaLog.cs
src/LodeRunner.API/src/Core/Startup.cs
src/LodeRunner.API/src/HealthChecks/CosmosHealthCheck.cs
src/LodeRunner.Core/LodeRunner.Core.csproj
src/LodeRunner.Data/LodeRunner.Data.csproj
src/LodeRunner/LodeRunner.csproj
src/LodeRunner/src/ValidationTest/Main.cs

- Reviewed and updated packages to newest stable versions compatible with .Net5.0. 
- Made minor code changes to replace deprecated code. 
- Fixed minor error in LodeRunner.API README. 
- Omitted the following package updates due to incompatibility with VS 2019 (they caused VS 2019 to [generate warnings on compilation](https://github.com/dotnet/roslyn/issues/56738)):
> - Microsoft.Extensions.Configuration.Json: 5.0.0 --> 6.0.0
> - Microsoft.Extensions.Logging.Abstractions: 5.0.0 --> 6.0.0
- Closes retaildevcrews/wcnp/issues/556

Reviewed and updated packages

---

.github/workflows/loderunner-api.yaml
.github/workflows/loderunner-main-pr.yaml

Run Integration Test Cases In CI/CD
- Closes https://github.com/retaildevcrews/wcnp/issues/550

Run Integration Test Cases In CI/CD

---

.github/workflows/loderunner-only.yaml

Update CI/CD in loderunner to use autogitops docker
- References https://github.com/retaildevcrews/wcnp/issues/583

Changed autogitops workflow to use docker

---

autogitops/autogitops.json

To include new asb dev clusters west and east
- References https://github.com/retaildevcrews/wcnp/issues/568

Added east and westus2 targets to loderunner

---

src/LodeRunner.Core/Models/LoadClient.cs

Implemented new naming convention for load clients in LodeRunner UI
- Closes retaildevcrews/wcnp/issues/453

updated load client name

---

src/LodeRunner.Core/Models/ExceptionLogEntry.cs
src/LodeRunner.Data/CosmosDBRepository.cs

Log error messages from exceptions when trying to create and test cosmos client. When the exception is specific to Cosmos, add extra messages about potential causes for the user to check.
- Closes https://github.com/retaildevcrews/wcnp/issues/565

Log error messages from creating and testing Cosmos client

---

README.md
src/LodeRunner.API.Test/secrets/CosmosUrl
src/LodeRunner.API/secrets/CosmosUrl
src/LodeRunner.UI/src/components/ClientDetails/index.js
src/LodeRunner.UI/src/components/Clients/index.js
src/LodeRunner.UI/src/components/Clients/styles.css
src/LodeRunner.UI/src/components/ResultPage/index.js
src/LodeRunner.UI/src/components/ResultPage/styles.css
src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
src/LodeRunner.UI/src/components/ResultsOverviewPage/styles.css
src/LodeRunner.UI/src/components/TestPage/index.js
src/LodeRunner.UI/src/components/TestSubmission/index.js
src/LodeRunner.UI/src/models/index.js
src/LodeRunner.UI/src/utilities/datetime.js
src/LodeRunner.UI/src/utilities/datetime.test.js
src/LodeRunner/secrets/CosmosUrl

Remove mock data from ResultsOverview and Result pages LodeRunner.UI
- Closes [#issue_number (this will automatically close the issue when the PR closes)](https://github.com/retaildevcrews/wcnp/issues/558)

Remove mock data for TestRuns in LodeRunner.UI

---

autogitops/autogitops.json

To decomission old asb dev cluster reference for autogitops
- References https://github.com/retaildevcrews/wcnp/issues/568

Removed old asb dev cluster in autogitops config

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
src/LodeRunner.API.Test/IntegrationTests/Extensions/HttpClientExtension.cs
src/LodeRunner.Data/Interfaces/ITestRunService.cs
src/LodeRunner.Data/Services/TestRunService.cs
src/LodeRunner/README.md
src/LodeRunner/src/Services/LodeRunnerService.cs
src/LodeRunner/src/config.cs

- Adding polling mechanism to LodeRunner running in client mode
- Designed to poll every 10s for available TestRuns
- Client status is still updated every 5s
- Updated LodeRunner README 
- TODOs added to code:
- Implement execute test run function (https://github.com/retaildevcrews/wcnp/issues/585) (currently has a 20s placeholder delay to simulate test run)
- Add logic to sql query to check if current clientId is in ClientResults object (i.e. has already run the test)
- Incorporate better exception handling once NGSA logger is incorporated (https://github.com/retaildevcrews/wcnp/issues/582)
- New integration test will be added in a separate issue once the test execution function is implemented
- Closes https://github.com/retaildevcrews/wcnp/issues/551

Implement LodeRunner Service Polling Mechanism

---

README.md
src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
src/LodeRunner.UI/src/components/ResultsOverviewPage/styles.css
src/LodeRunner.UI/src/services/results.js

Enable Deletion of Test Runs
Test run deletion prevented if test run is in progress.
- Closes https://github.com/retaildevcrews/wcnp/issues/539

Delete TestRun in UI

---

src/LodeRunner.API/src/Controllers/ClientsController.cs
src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
src/LodeRunner.API/src/Controllers/TestRunsController.cs
src/LodeRunner.API/src/Core/SystemConstants.cs
src/LodeRunner.API/src/Extensions/ClientStatusServiceExtensions.cs
src/LodeRunner.API/src/Extensions/LoadTestConfigServiceExtensions.cs
src/LodeRunner.API/src/Extensions/TestRunsServiceExtensions.cs
src/LodeRunner.API/src/Handlers/ResultHandler.cs

Creates the response for GET (all) across endpoints.
- References https://github.com/retaildevcrews/wcnp/issues/581

Result handler for GET all responses

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
src/LodeRunner.API.Test/UnitTests/ValidateError.cs
src/LodeRunner.API/src/Controllers/ClientsController.cs
src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
src/LodeRunner.API/src/Controllers/TestRunsController.cs
src/LodeRunner.API/src/Core/SystemConstants.cs
src/LodeRunner.API/src/Extensions/ClientStatusServiceExtensions.cs
src/LodeRunner.API/src/Handlers/ResultHandler.cs
src/LodeRunner.API/src/Utilities/Parameters/ValidationError.cs
src/LodeRunner.Data/Services/BaseService.cs
src/LodeRunner.Data/Services/ClientStatusService.cs

Add CreateGetByIdResponse to LodeRunner.API ResultHandler and use in controllers
- References https://github.com/retaildevcrews/wcnp/issues/581

Add CreateGetByIdResponse to LodeRunner.API ResultHandler and use in controllers

---

README.md
src/LodeRunner.UI/README.md
src/LodeRunner.UI/src/services/utilities.js

Simplify LodeRunner.UI startup for users by automatically removing trailing slash for API URL
- Closes https://github.com/retaildevcrews/wcnp/issues/605

Automate Removing Trailing Slash

---

src/LodeRunner.Core/Events/ClientStatusEventArgs.cs
src/LodeRunner/src/Services/LodeRunnerService.cs
src/LodeRunner/src/Subscribers/ClientStatusUpdater.cs

Implemented code to handle status update exception.
- Closes https://github.com/retaildevcrews/wcnp/issues/591

Handle status update exception

---

autogitops/autogitops.json

Add new preprod clusters to the autogitops targets.
- References https://github.com/retaildevcrews/wcnp/issues/573

add autogitops config for new preprod envs

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
src/LodeRunner.API/src/Controllers/ClientsController.cs
src/LodeRunner.API/src/Extensions/ClientStatusServiceExtensions.cs

LR.API GetClients response needs to be reverted. Causing conflict with LR.UI
- Closes https://github.com/retaildevcrews/wcnp/issues/615

Bugfix - LR.API - Revert Get Clients Response

---

src/LodeRunner.UI/package-lock.json
src/LodeRunner.UI/package.json
src/LodeRunner.UI/src/services/utilities.js

Updated react-scripts version from 4.0.3 to 5.0.0 to update dependencies listed in dependabot alerts.
- Closes retaildevcrews/wcnp/issues/600

Updated react-scripts version

---

src/LodeRunner.UI/src/components/TestSubmission/index.js
src/LodeRunner.UI/src/services/testRun.js

- Closes https://github.com/retaildevcrews/wcnp/issues/611

LR.UI Create Test Run

---

.github/workflows/loderunner-api.yaml

Update dotnet run to use the standard output and removed unnecessary copy secrets commands
- Closes https://github.com/retaildevcrews/loderunner/issues/154
- References: https://github.com/retaildevcrews/wcnp/issues/586
- References: https://github.com/retaildevcrews/wcnp/issues/608

Update dotnet run to use the standard output and removed unnecessary copy secrets commands

---

docs/DataDictionary.md
src/LodeRunner.API.Test/IntegrationTests/Extensions/LoadTestConfigExtension.cs
src/LodeRunner.Core/Models/BaseEntityModel.cs
src/LodeRunner.Core/Models/ClientStatus.cs
src/LodeRunner.Core/Models/LoadClient.cs
src/LodeRunner.Core/Models/LoadTestConfig.cs
src/LodeRunner.Core/Models/LoadTestConfigPayload.cs
src/LodeRunner.Core/Models/TestRun.cs
src/LodeRunner.Core/Models/TestRunPayload.cs
src/LodeRunner/README.md

- Closes https://github.com/retaildevcrews/wcnp/issues/601

Update all models with required attribute

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs

Fixed Integration Test "CanDeleteTestRunById"
- Closes https://github.com/retaildevcrews/wcnp/issues/633

Fixed Integration Test "CanDeleteTestRunById"

---

.github/workflows/loderunner-api.yaml

Add secrets to LR.API workflow for ghcr

---

.github/workflows/loderunner-api.yaml

Include version in lr-api tag push

---

.github/workflows/loderunner-api.yaml

- References https://github.com/retaildevcrews/wcnp/issues/623

Remove requirement for ghcr_{id|pat} variables for lr api workflow

---

autogitops/autogitops.json

To remove target reference of old preprod cluster
- References https://github.com/retaildevcrews/wcnp/issues/620

Deleted old preprod cluster target

---

.github/workflows/loderunner-ui.yaml

Github action to build image/package for LR UI

---

src/LodeRunner.API/src/Controllers/ClientsController.cs
src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
src/LodeRunner.API/src/Controllers/TestRunsController.cs
src/LodeRunner.API/src/Core/SystemConstants.cs
src/LodeRunner.API/src/Handlers/ResultHandler.cs

- Added CreateDeleteResponse to ResultHandler
- Refactored GET, POST and DELETE response methods
References #https://github.com/retaildevcrews/wcnp/issues/581

Added CreateDeleteResponse to ResultHandler, Refactored GET, POST and DELETE response methods

---

.github/workflows/loderunner-ui.yaml

Update lR UI github action build target image and removed version request

---

.github/workflows/loderunner-ui.yaml
src/LodeRunner.UI/package.json

Populate verison in LR UI for github action main push

---

src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/ProcessContext.cs
src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs
src/LodeRunner.API.Test/IntegrationTests/Extensions/TestRunPayloadExtension.cs
src/LodeRunner.API/src/Core/Startup.cs
src/LodeRunner.API/src/Core/SystemConstants.cs
src/LodeRunner.Core/SystemConstants.cs
src/LodeRunner.Data/Interfaces/ITestRunService.cs
src/LodeRunner.Data/Services/TestRunService.cs
src/LodeRunner/src/Services/LodeRunnerService.cs
src/LodeRunner/src/ValidationTest/Main.cs

Bug fix: LodeRunner needs to poll TestRuns by LoadClient.Id
- Closes https://github.com/retaildevcrews/wcnp/issues/660

Bug fix: LodeRunner needs to poll TestRuns by LoadClient.Id

---

.github/workflows/loderunner-ui.yaml
Makefile
src/LodeRunner.UI/.env.production
src/LodeRunner.UI/Dockerfile
src/LodeRunner.UI/start-nginx.sh

- Added start-nginx.sh for envsubst and container entrypoint
- Removed nginx-dev Dockerfile target
- Added LRUI_DNS env var to be replaced
- Removed Dockerfile target, hence old Makefile won't work
- Changed Container default entrypoint
- Closes https://github.com/retaildevcrews/wcnp/issues/663

Added start-nginx.sh for envsubst

---

src/LodeRunner.UI/start-nginx.sh

start-nginx script replaces everything it thinks is a variable, instead of just LRAPI_DNS
- References https://github.com/orgs/retaildevcrews/projects/12#card-78564413

Update LR.API script to replace LRAPI_DNS variable

---

.github/workflows/loderunner-main-push.yaml

Update workflow to include sh files for LR.UI image build

---

.github/workflows/loderunner-main-push.yaml
src/LodeRunner.UI/Dockerfile
src/LodeRunner.UI/nginx.conf

Allow LR.UI routing w/ Virtual Service

Allow LR.UI routing w/ Virtual Service

---

src/LodeRunner.UI/package.json
src/LodeRunner.UI/src/services/utilities.js

Add Correlation Vector in each request header to support tracing abilities
- Closes https://github.com/retaildevcrews/wcnp/issues/654

Send Correlation Vector On All Requests from LR.UI

---

autogitops/autogitops.json
autogitops/dev/loderunner-ui.yaml

Add LR.UI deployment files for dev.
- Closes https://github.com/retaildevcrews/wcnp/issues/663

Add LR.UI deployment files for dev.

---

README.md
deploy/loderunner/local/4-loderunner-ui.yaml
src/LodeRunner.UI/package-lock.json

Update LR.UI for local dev cluster

---

src/LodeRunner.API/src/Core/Startup.cs
src/LodeRunner.API/src/Core/SystemConstants.cs

Fix of CORS for LR.UI
- Closes https://github.com/retaildevcrews/wcnp/issues/651

CORS BugFix - Enable CORS in Local Development

---

src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs

Added request payload to request logs
- Closes [issue_number (this will automatically close the issue when the PR closes)](https://github.com/retaildevcrews/wcnp/issues/658)

Added Request Payload to Request Logs

---

.github/workflows/loderunner-api.yaml
.github/workflows/loderunner-main-push.yaml
.github/workflows/loderunner-only.yaml
.github/workflows/loderunner-ui.yaml

- Add autogitops pull and gitops deploy to LR API and UI
- Push LodeRuner tag and push ngsa-lr:beta image to ghcr
- References https://github.com/retaildevcrews/wcnp/issues/662

Add autogitops pull and gitops deploy to LR API and UI. Tag and push LR to ghcr.

---

autogitops/preprod/loderunner.yaml

To fix bug on variable name for autogitops
- Closes https://github.com/retaildevcrews/wcnp/issues/692

Fixed image reference for loderunner

---

src/LodeRunner.UI/src/components/ConfigForm/ArrayOfStringInput/index.js
src/LodeRunner.UI/src/components/ConfigPage/index.js
src/LodeRunner.UI/src/components/CreateConfig/index.js
src/LodeRunner.UI/src/components/TestSubmission/index.js

Refactor Config Form in LR.UI
Missing refactor commits
- References https://github.com/retaildevcrews/wcnp/issues/650

Refactor Config Form in LR.UI

---

src/LodeRunner.API/src/Controllers/LoadTestConfigsController.cs
src/LodeRunner.API/src/Controllers/TestRunsController.cs
src/LodeRunner.API/src/Extensions/AutoMapperProfileExtensions.cs
src/LodeRunner.API/src/Handlers/ResultHandler.cs
src/LodeRunner.Core/Automapper/AutoMapperExtension.cs
src/LodeRunner.Core/Automapper/BasePayloadToEntityAutoMapperHelper.cs

Fixed bug : Unable to Update LoadTestConfig
- Closes https://github.com/retaildevcrews/wcnp/issues/694

Fixed bug : Unable to Update LoadTestConfig

---

src/LodeRunner.API/src/Handlers/ResultHandler.cs

Refactor: ResultHandler.CreatePutResponse to utilize method TryCatchException() and avoid the double cast operation " var existingItem = (TEntity)((ObjectResult)existingItemResp).Value;"
- Closes https://github.com/retaildevcrews/wcnp/issues/704

Refactor ResultHandler.CreatePutResponse

---

src/LodeRunner/Properties/launchSettings.json
src/LodeRunner/README.md

Updated docs and launchsettings.json to reflect latest dev cluster urls
- Closes https://github.com/retaildevcrews/wcnp/issues/602

Updated docs and launchsettings.json to reflect latest dev cluster urls

---

src/LodeRunner.Core/SchemaFilters/LoadTestConfigPayloadSchemaFilter.cs
src/LodeRunner.Core/SchemaFilters/LoadTestConfigSchemaFilter.cs
src/LodeRunner.Core/SchemaFilters/TestRunPayloadSchemaFilter.cs
src/LodeRunner.Core/SchemaFilters/TestRunSchemaFilter.cs

Remove 'delayStart' attribute from LoadTestConfig payload sample 
- Closes https://github.com/retaildevcrews/wcnp/issues/702

Remove 'delayStart' attribute from LoadTestConfig payload sample 

---

docs/DataDictionary.md
src/LodeRunner.Core/CommandLine/Parsers.cs
src/LodeRunner/README.md

Update LodeRunner --help message default values
- Closes https://github.com/retaildevcrews/wcnp/issues/703

Update LodeRunner --help message default values

---

README.md
mlc_config.json

Update documentation to provide steps to execute an example test run, including viewing load spike in Grafana dashboard
- Closes https://github.com/retaildevcrews/wcnp/issues/700

Document full test run steps with dashboard view

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
src/LodeRunner.API/src/Controllers/TestRunsController.cs

LoadTestConfig Validation is missing for TestRun POST and PUT
- Closes https://github.com/retaildevcrews/wcnp/issues/705

Add LoadTestConfig Validation for TestRun POST and PUT

---

README.md

Fill in Prometheus TODO on how to view impact of Loderunner test runs in the Prometheus dashboard.
- Closes https://github.com/retaildevcrews/wcnp/issues/730

Update Prometheus TODO in observability docs

---

src/LodeRunner.API.Test/IntegrationTests/Controllers/Clients.cs
src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs
src/LodeRunner.API/LodeRunner.API.csproj
src/LodeRunner.API/src/Handlers/ResultHandler.cs
src/LodeRunner.API/src/Program.cs
src/LodeRunner.Data/Interfaces/ICosmosDBRepository.cs
src/LodeRunner.Data/Services/BaseService.cs
src/LodeRunner.Data/Services/TestRunService.cs
src/LodeRunner.UI/package-lock.json
src/LodeRunner.UI/package.json
src/LodeRunner.UI/src/components/TestSubmission/index.js
src/LodeRunner.UI/src/models/configs.js
src/LodeRunner.UI/src/models/index.js
src/LodeRunner.UI/src/services/configs.test.js
src/LodeRunner/LodeRunner.csproj
src/LodeRunner/src/Services/LodeRunnerService.cs
src/LodeRunner/src/Subscribers/ClientStatusUpdater.cs
src/LodeRunner/src/core/Startup.cs

M4 Checklist items: TODO cleanup and Version update for LodeRunner and LodeRunner.API
- Closes https://github.com/retaildevcrews/wcnp/issues/763

M4 Checklist items: TODO cleanup and Version update for LodeRunner and LodeRunner.API

---

.github/workflows/loderunner-main-push.yaml
.github/workflows/mdlinkcheck.yml

Change autogitops image from bartr/autogitops:beta to retaildevcrews/autogitops:0.3.0
- Closes https://github.com/retaildevcrews/wcnp/issues/777

Use retaildevcrews v0.3.0 image for autogitops

---

autogitops/dev/loderunner-commandmode.yaml

- Fix checkov yaml issues in loderunner deployment template.
- References https://github.com/retaildevcrews/wcnp/issues/637

Loderunner checkov yaml fixes

---

autogitops/preprod/loderunner.yaml

- Fix checkov yaml issues in loderunner deployment template.
- References https://github.com/retaildevcrews/wcnp/issues/637

Port loderunner checkov fixes to preprod after testing in dev

---

src/LodeRunner.API/LodeRunner.API.csproj
src/LodeRunner.API/src/Core/Startup.cs
src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
src/LodeRunner.API/src/Program.cs

Add trace ID and span ID to the response headers.
If has a trace ID in request header, response header should use the same trace ID.
Log the trace and span ID.
- Closes https://github.com/retaildevcrews/wcnp/issues/802

Add OpenTelemetry tracer to API headers

---

src/LodeRunner.UI/src/services/utilities.js

Adding support for b3 tracing headers with eventual plans to retire MS Correlation Vector.
- Closes https://github.com/retaildevcrews/wcnp/issues/801

Add OpenTelemetry b3 Header Propagation

---

src/LodeRunner.UI/src/components/ClientDetails/index.js

Remove edit feature from LR.UI for the client name in details.
- Closes https://github.com/retaildevcrews/wcnp/issues/836

Remove edit feature from LR.UI for the client name in details.

---

src/LodeRunner.UI/src/components/App/styles.css
src/LodeRunner.UI/src/components/Configs/index.js
src/LodeRunner.UI/src/services/utilities.js

Open config detail by selecting config from list in LR.UI
- Closes https://github.com/retaildevcrews/wcnp/issues/835

Open config detail by selecting config from list in LR.UI

---

src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js

To follow standards in other pages, clicking on a test run in the Test Run Page should open it (not just the pencil icon).
- Closes https://github.com/retaildevcrews/wcnp/issues/833

Open Test Run Details By Clicking Card

---

src/LodeRunner.UI/src/components/ConfigForm/index.js
src/LodeRunner.UI/src/components/ResultPage/index.js
src/LodeRunner.UI/src/components/TestSubmission/index.js

Need to update field labels to make load test config page more intuitive in Loderunner UI. Updated labels on load test config create and edit pages.
- Closes retaildevcrews/wcnp/issues/834

Load Test Config UI updates

---

autogitops/dev/loderunner-api.yaml
autogitops/dev/loderunner-clientmode.yaml
autogitops/dev/loderunner-ui.yaml

Checkov fixes for LR Clientmode, API and UI
- References https://github.com/retaildevcrews/wcnp/issues/637

Checkov fixes for LR Clientmode, API and UI

---

autogitops/dev/loderunner-clientmode.yaml

Fix Checkov linter error exceptions for clientmode

Checkov exceptions for LR client mode

---

src/LodeRunner.UI/src/components/Modal/index.js
src/LodeRunner.UI/src/components/Modal/styles.css
src/LodeRunner.UI/src/components/ResultPage/index.js
src/LodeRunner.UI/src/components/ResultPage/styles.css
src/LodeRunner.UI/src/components/ResultsOverviewPage/index.js
src/LodeRunner.UI/src/components/TestSubmission/index.js

Redesign LR.UI detailed test run result page
- Closes https://github.com/retaildevcrews/wcnp/issues/832

Redesign LR.UI detailed test run result page

---

.github/workflows/loderunner-api.yaml
.github/workflows/loderunner-only.yaml
.github/workflows/loderunner-ui.yaml

Update the different Loderunner workflow files to check when a container stops unexpectedly. If so, print the logs of the container for a better debugging experience.
- Closes https://github.com/retaildevcrews/wcnp/issues/808

Show logs from detached container when it stops unexpectedly.

---

src/LodeRunner/src/Services/LodeRunnerService.cs

To ensure that all exceptions in ExecuteNewTestRunAsync were being handled and logged.
- Closes #retaildevcrews/wcnp/issues/861

Added exception logging to ExecuteNewTestRunAsync

---

.github/workflows/loderunner-main-pr.yaml
.github/workflows/loderunner-main-push.yaml
.github/workflows/scheduled_mdlinkcheck.yaml
docs/cosmos.md
src/LodeRunner.API.Test/IntegrationTests/Controllers/LoadTestConfigs.cs
src/LodeRunner.API.Test/IntegrationTests/Controllers/TestRuns.cs

- [] Code changes
- Updated keys in github workflow to use test cosmos db. 
- Removed card creation code in scheduled link check to address security concerns. 
- retaildevcrews/wcnp/issues/748
- Updated comments for integration tests, which need to be updated. See deprioritized issues in backlog: 
- retaildevcrews/wcnp/issues/866 
- retaildevcrews/wcnp/issues/867
- Closes retaildevcrews/wcnp/issues/807
- Closes retaildevcrews/wcnp/issues/809
- References retaildevcrews/wcnp/issues/867
- References retaildevcrews/wcnp/issues/866
- References retaildevcrews/wcnp/issues/748

Updated secrets in workflow, turned off card creation in scheduled link check

---

src/LodeRunner.API/src/Handlers/RequestLogger/RequestLogger.cs
src/LodeRunner/src/ValidationTest/Main.cs

Ensure all paths for run-loop and run-once use UpdateTestRun event
- Closes https://github.com/retaildevcrews/wcnp/issues/857

Ensure all paths for run-loop and run-once use UpdateTestRun event

---

.github/workflows/loderunner-api.yaml
.github/workflows/loderunner-only.yaml
.github/workflows/loderunner-ui.yaml

To add Grype vulnerability Scanner
- Closes https://github.com/retaildevcrews/wcnp/issues/905

Added Grype vulnerability scanner

---

src/LodeRunner/src/Services/LodeRunnerService.cs

Ensure TestRunId Is Present For All Requests In Logs.
Confirmed requests from Client Mode Are logging TestRunId.
Requests coming from Command Mode do not have a Test Run associated with them but we would still like to group requests therefore one is created.
Before Change:
After Change: 
- Closes https://github.com/retaildevcrews/wcnp/issues/895

Log TestRunId For Command Mode Requests

---

mlc_config.json

Added httpHeaders to mlc_config.json to ensure live links are not flagged as dead links in PR checks.
- Closes https://github.com/retaildevcrews/wcnp/issues/906

Markdown Link Check Action bug fix

---

.devcontainer/devcontainer.json
README.md

Added instructions to ReadMe on how to set port visibility and updated the names of some ports.
- Closes https://github.com/retaildevcrews/wcnp/issues/859

Set Port Visibility

---

README.md

Updated instructions to run integration tests in CodeSpaces
- Closes retaildevcrews/wcnp/issues/890

updated instructions to run integration tests in CodeSpaces

---

.devcontainer/post-start.sh
.gitignore
.vscode/tasks.json
README.md

Add Checkov VS code Task to Codespaces and populate a summary section at the end.
- Closes https://github.com/retaildevcrews/wcnp/issues/848
- Closes https://github.com/retaildevcrews/wcnp/issues/909

Add Checkov VS code Task to Codespaces and populate a summary section.

---

src/LodeRunner.Core/NgsaLogger/NgsaLogger.cs

Add a mechanism to check and handle inner exception at the main exception handler 

---

.github/workflows/loderunner-only.yaml
src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs

- Update "loderunner-only.yaml" workflow to execute LodeRunner.API Integration Testing step
- Remove B3ParentSpanId check/field from Integration Test
- Closes https://github.com/retaildevcrews/loderunner/issues/290

Update "loderunner-only.yaml" workflow to execute LodeRunner.API Integration Testing step

---

autogitops/dev/loderunner-api.yaml
autogitops/dev/loderunner-ui.yaml

- increase app replicas from 1 to 2
- add the default deployment update strategy to the yaml for self-documentation
- this is already the default behavior, so no changes here
- References https://github.com/retaildevcrews/wcnp/issues/722

dev: Update app deployments for improved resiliency

---

src/LodeRunner.Core/Models/TestRunPayload.cs

BugFix - HardStop and HardStopTime Not Being Set By Put TestRun
- Closes https://github.com/retaildevcrews/wcnp/issues/998

Added missing payload fields to TestPayload

---

autogitops/dev/loderunner-api.yaml
autogitops/dev/loderunner-clientmode.yaml
autogitops/dev/loderunner-commandmode.yaml
autogitops/dev/loderunner-ui.yaml
autogitops/preprod/loderunner-api.yaml
autogitops/preprod/loderunner-clientmode.yaml
autogitops/preprod/loderunner-commandmode.yaml
autogitops/preprod/loderunner-ui.yaml

- updated resource and request limits for loderunner deployments within the autogitops folder
- Closes https://github.com/retaildevcrews/wcnp/issues/1014
- References https://github.com/retaildevcrews/wcnp/issues/1001

Updating resource limits for Loderunner AutoGitOps

---

src/LodeRunner.Data/Services/TestRunService.cs

Fix Bug: LodeRunner TestRun Service is not filtering out cancelled TestRuns
- Closes  https://github.com/retaildevcrews/loderunner/issues/305

Fix bug: LodeRunner TestRun Service is not filtering out cancelled TestRuns

---

src/LodeRunner.API/src/Core/Startup.cs

GetTestRuns causes LodeRunner's Swagger UI to crash because it returns a large number of items. However, the same GET request works on Postman. Updated Swagger UI config settings to speed up rendering by disabling syntax highlighting. Swagger UI no longer crashes.
- Closes retaildevcrews/wcnp/issues/1011

updated Swagger UI config 

---

docs/cosmos.md
scripts/stored-procedures/spBulkDelete.json

- Closes https://github.com/retaildevcrews/wcnp/issues/747

Document LodeRunnerDB Maintenance process 

---

.github/workflows/loderunner-api.yaml
.github/workflows/loderunner-only.yaml
.github/workflows/loderunner-ui.yaml
src/LodeRunner.API/LodeRunner.API.csproj
src/LodeRunner.Data/LodeRunner.Data.csproj
src/LodeRunner.UI/Dockerfile

- Fix dotnet CVEs by upgrading Microsoft.Azure.Cosmos from 3.27.1 to 3.31.1
- Actual issues is a dependency on System.Drawing.Common
- Fix curl CVEs by upgrading apk packages in Dockerfile base off nginx
- Closes https://github.com/retaildevcrews/wcnp/issues/1059

Fix Loderunner issues found by Grype scan

---

.github/workflows/scheduled_mdlinkcheck.yaml
docs/DataDictionary.md
docs/WorkingAgreement.md

Updated md file to fix a broken link. Also updated the version of the "create issue" action that runs with the scheduled link check, as the old version was failing to create the issue.
- Closes retaildevcrews/wcnp/issues/1132

Fixed broken link, updated "create issue" action version

---

autogitops/dev/loderunner-api.yaml
autogitops/dev/loderunner-clientmode.yaml
autogitops/dev/loderunner-ui.yaml
autogitops/preprod/loderunner-api.yaml
autogitops/preprod/loderunner-clientmode.yaml
autogitops/preprod/loderunner-ui.yaml

- References https://github.com/retaildevcrews/wcnp/issues/1152

Update NodeSelector to use Node Type

---

src/LodeRunner.UI/Dockerfile

- Closes https://github.com/retaildevcrews/wcnp/issues/1160

Updated curl and libcurl version
