retaildevcrews/loderunner

Program.cs, aspnetapp.csproj, core/Startup.cs
- moved sigterm to webhost instead of console
- sigterm from k8s wasn't handled because of the addition of /metrics
=> moved sigterm to web host

Ngsa.DataAccessLayer/Ngsa.DataAccessLayer.csproj, Ngsa.LodeRunner.csproj
By disabling these flags the loderunner build should successfully complete 
Closes [Issue #329](https://github.com/retaildevcrews/wcnp/issues/329)
=> Disabled EnableNETAnalyzers and EnforceCodeStyleInBuild settings

src/Program.cs, src/core/Startup.cs
Fixed logic to correctly intercept Ctrl+C and OnAppClose events to intiate Cancellation Token Request with out Windows Native dlls dependencies.
Testing 
-  delay-star = -1
-  run-loop true
-  delay-star = 5
Closes [issue #330](https://github.com/retaildevcrews/wcnp/issues/330)
=> Fixed logic to correctly intercept Ctrl+C and OnAppClose events

src/LodeRunner.API/LodeRunnerApi.xml, src/LodeRunner.API/src/Controllers/LoadTestConfigController.cs, src/LodeRunner.API/src/Extensions/ModelExtensions.cs, src/LodeRunner.Core/CommandLine/LRCommandLine.cs, src/LodeRunner.Core/LodeRunner.Core.xml, src/LodeRunner.Core/Models/LoadTestConfig.cs, src/LodeRunner.Core/Models/LoadTestConfigPayload.cs, src/LodeRunner.Test/UnitTests/CommandLineArgs.cs
- Fix bug LodeRunner.API 500 when only required values are POSTed
- Also fixed a found undercover bug related to incorrect conversion from Payload properties to arguments. 
For instance, if we want to create a new load test config with the only 2 arguments e.g. Server and Files, at the time we convert the payload to arguments list, the previous logic was looping thru all payload DTO properties and as a result arguments array included all possible ones with default values which was not the intent at the time, we submitted the create request , that ended up on several command line argument parsing validations to fail.
- Closes #501
=> Fix bug LodeRunner.API 500 when only required values are POSTed

src/LodeRunner.UI/src/components/Clients/index.js, src/LodeRunner.UI/src/components/Clients/styles.css
Update the Clients component in the UI to render the message, No Load Clients Available, when the UI does not have clients to render. The UI renders the same as before if clients are available.
- Closes https://github.com/retaildevcrews/wcnp/issues/508
=> Update LodeRunner.UI to display a message when no clients are available

src/LodeRunner.UI/src/components/ConfigForm/IntegerInput/index.js, src/LodeRunner.UI/src/components/ConfigForm/index.js
Max Errors Will Only Appear on Form if Run Loop is Disabled
- Closes https://github.com/retaildevcrews/wcnp/issues/562
=> Only Display Max Errors When Run Loop Is Disabled

.github/workflows/loderunner-ui.yaml, src/LodeRunner.UI/package.json
This reverts commit 1a42f81a5d9ea5a5742b9d9aeb53402a5525e980.
Get github workflow/action working for main push: building loderunner ui image
=> Revert "Populate version in LR UI for github action main push (#178)"

src/LodeRunner.UI/src/components/Modal/index.js, src/LodeRunner.UI/src/components/Modal/styles.css
- make modal overlay and modal content siblings instead of parent-child
- default click handler can now differentiate between targets when clicking inside and releasing outside the modal
- Closes https://github.com/retaildevcrews/wcnp/issues/838
=> Fix UI issue where modal can be closed by clicking in the modal and releasing outside the modal

.devcontainer/cosmos-emulator/setup-cosmos-emulator.sh, .devcontainer/cosmos-emulator/start-cosmos-emulator.sh
When resuming codespace, cosmos emulator doesn't find the certificate.
Because the certificate sometimes gets deleted after prolonged codespace sleep, it needs to be installed again.
- Closes https://github.com/retaildevcrews/wcnp/issues/844
=> Bugfix: Cosmos Emulator's sleep disorder

.github/workflows/markdownlint.yml, README.md
Currently MDLint check runs on all branches on push.
Markdown Lint Action should only run for
- Pull Request [Open, Synchronize]
- Push/Merge on `main`
- Closes https://github.com/retaildevcrews/wcnp/issues/842
=> Run MDLint on PRs only 

src/LodeRunner.UI/package-lock.json, src/LodeRunner.UI/package.json
LodeRunner.UI linter had conflict about where to pull from. disabling eslint plugin when starting application so it can pull from airbnb rules instead.
- Closes https://github.com/retaildevcrews/wcnp/issues/852
=> LodeRunner.UI - Fix Lint Rules Conflict

.devcontainer/on-create.sh, .devcontainer/post-create.sh
To move the cosmos emulator create script to onCreate to enable Codespaces prebuild
- Closes https://github.com/retaildevcrews/wcnp/issues/855
=> Move Cosmos Emulator setup to onCreate for Prebuild

.devcontainer/devcontainer.json, .devcontainer/on-create.sh, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, README.md, omnisharp.json
- Update Codespace C# development environment for Burst metrics
- Omnisharp settings update (global Roslyn settings and vscode specific)*
- VSCode editorconfig support*
- Added build tasks for LodeRunner.API, LodeRunner
- Added launch settings for LodeRunner and LodeRunner.API
- IDE improvements (sort `using`)
- Added dotnet test explorer
- Closes https://github.com/retaildevcrews/wcnp/issues/873
=> Add Codespace .NET dev environment for LodeRunner repo

.devcontainer/Dockerfile, .devcontainer/cosmos-emulator/Dockerfile, .github/workflows/checkov-docker.yml, src/LodeRunner.API/Dockerfile, src/LodeRunner.UI/Dockerfile, src/LodeRunner/Dockerfile
Added Checkov action to CI/CD workflow to run on Dockerfiles
- Closes retaildevcrews/wcnp/issues/860
=> added checkov action, skip statements

src/LodeRunner.API/src/.editorconfig, src/LodeRunner/src/.editorconfig
Remove CRLF configuration which is missing from the line ending PR.
With this change, VSCode will not convert the line ending to CRLF automatically.
- Closes https://github.com/retaildevcrews/wcnp/issues/874
=> Removed CRLF configuration from editorconfig

src/LodeRunner/src/ValidationTest/Main.cs, src/LodeRunner/src/ValidationTest/Model/PerfLog.cs
ParentSpanID is not required to be logged in LodeRunner as it originates requests and does not having parent tracing information.
- References https://github.com/retaildevcrews/wcnp/issues/882
- Closes https://github.com/retaildevcrews/wcnp/issues/925
=> BugFix - Remove ParentSpanID from LodeRunner

src/LodeRunner.API.Test/IntegrationTests/ExecutingTestRun/TestRunExecution.cs, src/LodeRunner.API/src/Core/Startup.cs, src/LodeRunner.API/src/Program.cs, src/LodeRunner/src/Program.cs, src/LodeRunner/src/Services/LodeRunnerService.cs, src/LodeRunner/src/ValidationTest/ReadValidateJson.cs, src/LodeRunner/src/ValidationTest/Validators/ResponseValidator.cs, src/LodeRunner/src/config.cs, src/LodeRunner/src/core/Startup.cs
- Makes Program.cs file idiomatic and removes unnecessary partial declarations.
- Removed ParentSpanID from integration tests
- It was removed with this PR: https://github.com/retaildevcrews/loderunner/pull/289
- Closes https://github.com/retaildevcrews/wcnp/issues/922
=> LodeRunner & LodeRunner.API App Declaration

README.md
Modified the README in the 'Running the System via Codespaces' section to ensure that the instructions to access LodeRunner.UI is correct and consistent across different Codespaces environments - both browser and VS Code.
- Closes https://github.com/retaildevcrews/wcnp/issues/971
=> Access LodeRunner.UI: Inconsistency between Codespaces in Browser & VSCode

src/LodeRunner.UI/src/components/ConfigPage/index.js
Fixes an issue when viewing/editing a Load Test Config where boolean inputs in the form default to false instead of loading appropriate value.
- Closes https://github.com/retaildevcrews/wcnp/issues/1002
=> LR.UI Bug - RunLoop always shows false when view a config

.github/workflows/loderunner-api.yaml, .github/workflows/loderunner-only.yaml, .github/workflows/loderunner-ui.yaml
- Closes https://github.com/retaildevcrews/loderunner/issues/312
=> Remove "acs-report-enable" action input from vulnerability scan action as it is no longer an allowed action input

autogitops/dev/loderunner-pod-identity.yaml, autogitops/preprod/loderunner-pod-identity.yaml
Updating gitops templates to remove hardcoded keyvault names. Keyvault names from old subscription were hardcoded in autogitops template, causing loderunner to fail in new subscription.
- Closes retaildevcrews/wcnp/issues/1117
- Closes #326 
- References retaildevcrews/wcnp/issues/1028
- References retaildevcrews/wcnp/issues/1055
=> Parameterized keyvault names in loderunner-pod-identity.yaml autogitops template
